name: Build Adguardfilter
on:
  schedule:
        - cron: '30 17 * * 0-6'
  workflow_dispatch:
jobs:
  adguardfilter_build:
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
        working-directory: .\Adguard-Filter
    steps:
      - uses: actions/checkout@v6
      - name: Install HostlistCompiler
        run: npm i -g @adguard/hostlist-compiler      
      - name: Build Adguard list
        run: hostlist-compiler -c configuration5.json -o Adguardstylepc.txt
        
      - name: upload
        run: |
          git config --global user.name 'unknown4849'
          git config --global user.email '74445408+unknown4849@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add Adguardstylepc.txt
          git commit -m "update"
          git push
          
  dnscrypt_build:
    runs-on: windows-latest
    needs: adguardfilter_build
    defaults:
      run:
        shell: bash
        working-directory: .\DNScrypt-Filter
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v6
    - uses: actions/setup-python@v6
      with:
        python-version: '3.10' 
    - run: py generate-domains-blocklist.py -o blocked-names.txt

    - name: upload
      run: |
          git config --global user.name 'unknown4849'
          git config --global user.email '74445408+unknown4849@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add blocked-names.txt
          git commit -m "update"
          git push
