name: Build dnsfilter
on:
  schedule:
        - cron: '00 03 * * 0-6'
          timezone: "Asia/Jakarta"
  workflow_dispatch:
jobs:
  adguardfilter:
    runs-on: windows-2025-vs2026
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Install HostlistCompiler
        run: npm i -g @adguard/hostlist-compiler
      - name: Build Adguard list
        working-directory: .\Adguard-Filter
        run: |
          hostlist-compiler -c configuration5.json -o Adguardstylepc.txt
          hostlist-compiler -c configuration.json -o Adguardstyle.txt
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.14'
      - name: Build blocked-names
        working-directory: .\DNScrypt-Filter
        run: |
          py generate-domains-blocklist.py -o blocked-names.txt
          git add blocked-names.txt
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@2dc316deee8e90f13e1a351ab510b4d5bc0c82cd # v7.0.0
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true
      - name: git add
        run: |
          git add -u
          git commit -m "update"
          git push
